# Email Configuration (Local Development - Disabled)

mailSender.protocol=smtp
mailSender.host=localhost
mailSender.port=25
mailSender.username=
mailSender.password=
mailSender.starttls=false
mailSender.auth=false

email.active=false
