# Shopizer Core Configuration for H2 Profile

# CMS Configuration
config.cms.contentUrl=
config.cms.imageUrl=

# File Storage (local)
config.cms.files.location=./files

# Search
config.search.enabled=false

# Cache
config.cache.enabled=true
