# Local dev - email disabled
mailSender.protocol=smtp
mailSender.host=localhost
mailSender.port=25
mailSender.username=
mailSender.password=
mailSender.mail.smtp.auth=false
mail.smtp.starttls.enable=false